### ISSUE TITLE
testWrite 方法单元测试请教

### ISSUE THREAD

**Issue by rust17** [overtrue/flysystem-cos#1]
https://github.com/overtrue/flysystem-cos/blob/7506d15878493667c3b319ed5e844667c4668e04/tests/CosAdapterTest.php#L49

请问此处的 `put()` 方法是在哪定义的？我在断点调试模式下测试发现此处报错了。正在学习单元测试，不是很懂这块，麻烦超哥解答下哈 😃 

![image](https://user-images.githubusercontent.com/16575052/54083037-8724d880-4359-11e9-9038-7fe1ea15dcf9.png)

**Comment by rust17** [comment]
不好意思，写错地方了

**Comment by overtrue** [comment]
哈哈
