### ISSUE TITLE
怎样和 Flarum 论坛的 fof upload 插件搭配

### ISSUE THREAD

**Issue by AnotiaWang** [overtrue/flysystem-cos#10]
如题，我想在 Flarum 论坛里用 fof upload 插件搭配这个插件实现上传文件到腾讯COS，请问应该怎么做？谢谢

**Comment by overtrue** [comment]
抱歉我没空研究它哦，你需要自己研究哈。

AnotiaWang <notifications@github.com>于2020年8月1日 周六上午10:23写道：

**Comment by AnotiaWang** [comment]
好吧😂😂
