### ISSUE TITLE
将配置文件 放在 filesystems.php 文件中 提示 driver 找不到。

### ISSUE THREAD

**Issue by gyp719** [overtrue/flysystem-cos#11]
将配置文件 放在 filesystems.php 文件中 提示 driver 找不到。  driver 应该设置为什么？

**Comment by overtrue** [comment]
我没办法仅凭“将配置文件 放在 filesystems.php 文件中 ” 想像出你是怎么配置的哈，建议脱敏贴出来

**Comment by gyp719** [comment]
```

        'cos' => [
            'driver' => 'flysystem-cos',  
            'region'          => 'ap-nanjing',
            'credentials'     => [
                'appId'     => 1300314322, // 域名中数字部分 1300314322
                'secretId'  => '',
                'secretKey' => '',
            ],
            'bucket'          => ',
            'timeout'         => 60,
            'connect_timeout' => 60,
            'cdn'             => '您的 CDN 域名',
            'scheme'          => 'https',
            'read_from_cdn'   => false,
        ],

```
driver 的值

**Comment by overtrue** [comment]
你这是自创的？文档没写清楚吗？https://github.com/overtrue/laravel-filesystem-cos
![image](https://user-images.githubusercontent.com/1472352/90586365-a17b0b00-e209-11ea-8a24-220b3c859e88.png)


<blockquote><img src="https://avatars1.githubusercontent.com/u/1472352?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/overtrue/laravel-filesystem-cos">overtrue/laravel-filesystem-cos</a></strong></div><div>Tencent Cloud COS storage for Laravel based on overtrue/flysystem-cos. - overtrue/laravel-filesystem-cos</div></blockquote>

**Comment by gyp719** [comment]
之前用的 是  composer require overtrue/flysystem-cos

使用 laravel 用 laravel 的 cos包， 文档：[](https://github.com/overtrue/laravel-filesystem-cos)
感谢 overtrue 的指导

**Comment by overtrue** [comment]
overtrue/flysystem-cos 这个包是为 PHP 使用的，没有 driver 参数：https://github.com/overtrue/flysystem-cos#usage

<blockquote><img src="https://avatars1.githubusercontent.com/u/1472352?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/overtrue/flysystem-cos">overtrue/flysystem-cos</a></strong></div><div>:floppy_disk: Flysystem adapter for the Qcloud COS storage. - overtrue/flysystem-cos</div></blockquote>
