### ISSUE TITLE
上传超过1M文件

### ISSUE THREAD

**Issue by cxjhk** [overtrue/flysystem-cos#17]
cURL error 0: The cURL request was retried 3 times and did not succeed. The most likely reason for the failure is that cURL was unable to rewind the body of the request and subsequent retries resulted in the same error. Turn on the debug option to see what went wrong. See https://bugs.php.net/bug.php?id=47204 for more information. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for 

上传超过1M的文件出现这个

使用的框架是hyperf 

上传到服务器本地是没有问题的而且上传小文件也是没有问题的 

swoole和php.ini的post配置也是改了的

**Comment by linyiyuan** [comment]
请问你解决了吗，我现在也遇到这个问题

**Comment by ljl360197197** [comment]
编译安装swoole需要加上 --enable-swoole-curl

**Comment by vzina** [comment]
Hyperf上传大文件建议：
swoole版本：>= 4.8

修改相关方法：
```
use League\Flysystem\Config;
use Overtrue\Flysystem\Cos\CosAdapter as OCosAdapter;

class CosAdapter extends OCosAdapter
{
    /**
     * @param string   $path
     * @param resource $resource
     * @param Config   $config
     *
     * @return array|false
     */
    public function writeStream($path, $resource, Config $config)
    {
        $options = $this->getUploadOptions($config);

        return $this->getClient()->upload($this->getBucket(), $path, $resource, $options['params']);
    }
}
```

**Comment by overtrue** [comment]
fpm 和 cli 模式下均不能复现，其它模式下请自行适配，先关了。
