### ISSUE TITLE
getUrl()只有半小时有效

### ISSUE THREAD

**Issue by ee01** [overtrue/flysystem-cos#25]
看到代码中只调用了getObjectUrl()，并且expire传空(默认30 mins)，如何获取永久link？

我看官网文档是调用getObjectUrlWithoutSign()方法。https://cloud.tencent.com/document/product/436/60480

<img width="535" alt="image" src="https://user-images.githubusercontent.com/2222227/179147287-5f19585d-c2ef-4950-a102-3443bb4b490f.png">

**Comment by ee01** [comment]
因为2.x版本开始就需要php 8.0.2，目前在用7.4，所以用的版本一直是1.0.0

<img width="606" alt="image" src="https://user-images.githubusercontent.com/2222227/179150949-653f2847-f4d5-4e94-abc9-0975ce2174c6.png">

后面的版本有解决这个半小时时效的问题？

**Comment by overtrue** [comment]
新版已经不用官方 SDK 了： https://github.com/overtrue/flysystem-cos/blob/master/src/CosAdapter.php#L312-L321

**Comment by ee01** [comment]
> 新版已经不用官方 SDK 了： https://github.com/overtrue/flysystem-cos/blob/master/src/CosAdapter.php#L312-L321

这个版本需要 php 8.0.2，有没有一个次新版本是php 7.x的？我试了2.0.0版本都说需要php 8.0.2

**Comment by overtrue** [comment]
@ee01 3.0.2 php >= 7.4
