### ISSUE TITLE
不能在PHP8.1中使用

### ISSUE THREAD

**Issue by Burial0268** [overtrue/flysystem-cos#30]
如题:
Deprecated: Return type of Overtrue\CosClient\Config::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/discuss/vendor/overtrue/qcloud-cos-client/src/Config.php on line 92

Deprecated: Return type of Overtrue\CosClient\Config::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/discuss/vendor/overtrue/qcloud-cos-client/src/Config.php on line 97

还有该文件的102,107行以及src/Http/Response.php的48,57.62,67,72行

虽然是Deprecated，但是还是希望作者能够适配下

**Comment by overtrue** [comment]
```
composer info overtrue/qcloud-cos-client
```

贴一下

**Comment by Burial0268** [comment]
name     : overtrue/qcloud-cos-client
descrip. : Client of QCloud.com COS
keywords :
versions : * 1.0.4
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage :
source   : []
dist     : [zip] https://mirrors.cloud.tencent.com/repository/composer/overtrue/qcloud-cos-client/1.0.4/overtrue-qcloud-cos-client-1.0.4.zip 64ca47881afe4fd0961958f85674dcae71421913
path     : /www/wwwroot/zerohikari.cn/vendor/overtrue/qcloud-cos-client
names    : overtrue/qcloud-cos-client

autoload
psr-4
Overtrue\CosClient\ => src

requires
ext-dom *
ext-json *
ext-libxml *
ext-simplexml *
guzzlehttp/guzzle ^7.2
php >=7.4
psr/http-message ^1.0

requires (dev)
brainmaestro/composer-git-hooks ^2.7
friendsofphp/php-cs-fixer ^3.4.0
mockery/mockery ^1.0
monolog/monolog ^2.1
phpunit/phpunit ^9.0

**Comment by Burial0268** [comment]
name     : overtrue/qcloud-cos-client
descrip. : Client of QCloud.com COS
keywords :
versions : * 1.0.4
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage :
source   : []
dist     : [zip] https://mirrors.cloud.tencent.com/repository/composer/overtrue/qcloud-cos-client/1.0.4/overtrue-qcloud-cos-client-1.0.4.zip 64ca47881afe4fd0961958f85674dcae71421913
path     : /www/forum/vendor/overtrue/qcloud-cos-client
names    : overtrue/qcloud-cos-client

autoload
psr-4
Overtrue\CosClient\ => src

requires
ext-dom *
ext-json *
ext-libxml *
ext-simplexml *
guzzlehttp/guzzle ^7.2
php >=7.4
psr/http-message ^1.0

requires (dev)
brainmaestro/composer-git-hooks ^2.7
friendsofphp/php-cs-fixer ^3.4.0
mockery/mockery ^1.0
monolog/monolog ^2.1
phpunit/phpunit ^9.0

**Comment by overtrue** [comment]
你用的旧版了，升级一下
