### ISSUE TITLE
腾讯云里面的 url 并没有 app_id

### ISSUE THREAD

**Issue by chenny** [overtrue/flysystem-cos#32]
腾讯云里面的 url 并没有 app_id,带上 app_id会出错,请问怎么处理
![image](https://user-images.githubusercontent.com/883329/228202850-10323cbf-1a44-46b6-a3fe-44d9bb5c119d.png)
<img width="505" alt="image" src="https://user-images.githubusercontent.com/883329/228203241-191420c5-f58b-43c1-8f9d-e9203f7536b4.png">

**Comment by overtrue** [comment]
数字就是appid

**Comment by pslxx** [comment]
的确错了,我都自定义了域名,不然直接报错 找不到bucket

**Comment by overtrue** [comment]
贴一下你的配置
