### ISSUE TITLE
listObjects 方法获取失败

### ISSUE THREAD

**Issue by lushaobo** [overtrue/flysystem-cos#37]
![image](https://github.com/overtrue/flysystem-cos/assets/5574978/1b196d2a-fd08-406c-ad23-7e7207017c33)

在测试获取目录的时候，发现无论传什么参数都返回空数组。检查代码的时，发现了此问题。

接口返回的xml结果最外层是使用 ListBucketResult  来包含的，但通过xml2arr 后，则已经没有了这一层

**Comment by overtrue** [comment]
感谢反馈，已修复并发版。
