### ISSUE TITLE
league/flysystem与Thinkphp8.0里的冲突。安装不了

### ISSUE THREAD

**Issue by ajaxjs** [overtrue/flysystem-cos#38]
Using version ^5.1 for overtrue/flysystem-cos
./composer.json has been updated
Running composer update overtrue/flysystem-cos
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - overtrue/flysystem-cos[5.1.0, ..., 5.1.8] require league/flysystem ^3.0 -> found league/flysystem[3.0.0, ..., 3.24.0] but the package is fixed to 2.5.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires overtrue/flysystem-cos ^5.1 -> satisfiable by overtrue/flysystem-cos[5.1.0, ..., 5.1.8].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require overtrue/flysystem-cos:*" to figure out if any version is installable, or "composer require overtrue/flysystem-cos:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by overtrue** [comment]
加 -W

**Comment by ajaxjs** [comment]
> 加 -W

加**-W**也不行，不过我删除**think-filesystem**后就好了。
