### ISSUE TITLE
用 $flysystem->write 上传文件后，如何获取上传成功的路径？

### ISSUE THREAD

**Issue by ajaxjs** [overtrue/flysystem-cos#39]
如题，是需要自己拼一个路径吗？
最好能返回文件路径， 大小等详细信息。

**Comment by overtrue** [comment]
这个是 flysystem 的插件，需要遵循 flysystem 的协议，返回值有规定哈

**Comment by ajaxjs** [comment]
请问，上传后如何获得地址呢？

**Comment by overtrue** [comment]
key 是你自己传的啊，cdn 地址或者桶的域名也是已知的不是么，连到一起不就是 url 了吗？🥹

**Comment by ajaxjs** [comment]
谢谢
