### ISSUE TITLE
visibility 方法有问题

### ISSUE THREAD

**Issue by pslxx** [overtrue/flysystem-cos#40]
<img width="1148" alt="image" src="https://github.com/overtrue/flysystem-cos/assets/8417207/f539fce8-d6b5-4d38-8ca7-50825bad5b22">

如图,这个地方获取acl权限,但是实际上腾讯云返回的都是xml格式,这个地方使用数组循环,肯定都是空
所以权限永远是private,导致livewire生成的地址也都是私有带签名的地址,
<img width="1011" alt="image" src="https://github.com/overtrue/flysystem-cos/assets/8417207/939439c7-eaa5-4853-b6b6-f2f7878ab2ef">

**Comment by overtrue** [comment]
感谢反馈，已修复：https://github.com/overtrue/flysystem-cos/commit/9a7b3beb117f2a510234c1e76373b5b515e258a6

**Comment by overtrue** [comment]
请更新到 5.1.9 https://github.com/overtrue/flysystem-cos/releases/tag/5.1.9
