### ISSUE TITLE
Plugins 文件夹没有打包到Tag里，请求失败

### ISSUE THREAD

**Issue by Jasongzj** [overtrue/flysystem-cos#9]
超哥，需要重新打个tag，现在调用现在调用 getUrl() 方法找不到文件

**Comment by overtrue** [comment]
https://github.com/overtrue/flysystem-cos/releases/tag/2.0.1

<blockquote><img src="https://avatars1.githubusercontent.com/u/1472352?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/overtrue/flysystem-cos/releases/tag/2.0.1">Release 2.0.1 · overtrue/flysystem-cos</a></strong></div><div>:floppy_disk: Flysystem adapter for the Qcloud COS storage. - overtrue/flysystem-cos</div></blockquote>
